### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by isabelneves** [lukanetconsult/mage-google-adwords#10]
I have installed the module but when I acess my dashboard ->configurate -> Google API
appears an white page with the message: Fatal error: Class 'LUKA_GoogleAdWords_Helper_Data' not found in /home/storage/c/a0/08/montesualistadecasam/public_html/app/Mage.php on line 546

How can I fix this? I have already log out and log in, cleanned my cache

Thanks 
Isabel

**Comment by tux-rampage** [comment]
Have you turned off the Compilation-Feature before installing as described here: 
https://github.com/lukanetconsult/mage-google-adwords/wiki/FAQ#im-experiencing-errors-after-installingupgrading-the-extension

**Comment by tux-rampage** [comment]
Since there was no negative feedback on this, we'll consider this resolved.
