### ISSUE TITLE
modman file?

### ISSUE THREAD

**Issue by abelmannu** [lukanetconsult/mage-google-adwords#14]
Could you create a modman file, please? The content would be:

app/code/community/LUKA/GoogleAdWords app/code/community/LUKA/GoogleAdWords
app/design/adminhtml/default/default/template/luka/google/adwords/config/conversions.phtml app/design/adminhtml/default/default/template/luka/google/adwords/config/conversions.phtml
app/design/frontend/base/default/layout/luka_googleadwords.xml app/design/frontend/base/default/layout/luka_googleadwords.xml
app/design/frontend/base/default/template/luka/google app/design/frontend/base/default/template/luka/google
app/etc/modules/LUKA_GoogleAdWords.xml app/etc/modules/LUKA_GoogleAdWords.xml
app/locale/de_DE/LUKA_GoogleAdWords.csv app/locale/de_DE/LUKA_GoogleAdWords.csv

**Comment by tux-rampage** [comment]
Sure, we're already doing this for our other modules since it works well along with composer.
