### ISSUE TITLE
Frontend templates do not belong in base folder

### ISSUE THREAD

**Issue by func0der** [lukanetconsult/mage-google-adwords#16]
The headline says it all. They belong in the default folder.

**Comment by tux-rampage** [comment]
This is not correct.

Since version 1.5 all module specific templates should go into base, since this is the final fallback when a theme does not provide it in its default path.

**Comment by func0der** [comment]
That might very well be true and I apologize for not knowing that.

Where did you get that information from? I must have missed it.

**Comment by tux-rampage** [comment]
It is stated in the Doc-Comment of Mage_Core_Model_Design_Packaged::_fallback(). Also the code shows that this is the case.

https://git.luka.de/magento/magento-core/blob/master/magento/app/code/core/Mage/Core/Model/Design/Package.php#L406
