### ISSUE TITLE
Plugin not work with Magento ver. 1.7.0.2

### ISSUE THREAD

**Issue by raffa84** [lukanetconsult/mage-google-adwords#9]
Hi, after the installation of plug-in, the configuration page not work.
It show me a white page.
Solution?

**Comment by tux-rampage** [comment]
Can you please provide some additional information?

* Are there any entries in the PHP error log (ensure that log_errors is on in php.ini)?
* Are you using the compilation feature? If so:
  - Did you follow the installation steps as described in the [FAQ](https://github.com/lukanetconsult/mage-google-adwords/wiki/FAQ#im-experiencing-errors-after-installingupgrading-the-extension).

**Comment by Mlinnig** [comment]
Just try to log out and then back in, should solve this

**Comment by tux-rampage** [comment]
Closed, because there was no response from op for more than 1 Month.
